/*
 *
 *  * Copyright (c) 2025 Dr. Andreas Feldner.
 *  *
 *  *     This program is free software; you can redistribute it and/or modify
 *  *     it under the terms of the GNU General Public License as published by
 *  *     the Free Software Foundation; either version 2 of the License, or
 *  *     (at your option) any later version.
 *  *
 *  *     This program is distributed in the hope that it will be useful,
 *  *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  *     GNU General Public License for more details.
 *  *
 *  *     You should have received a copy of the GNU General Public License along
 *  *     with this program; if not, write to the Free Software Foundation, Inc.,
 *  *     51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *  *
 *  * Contact information and current version at http://www.flying-snail.de/IPv6Droid
 *
 *
 */

package de.flyingsnail.ipv6droid.android;

import static android.view.View.VISIBLE;

import android.Manifest;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.SharedPreferences;
import android.net.Uri;
import android.net.VpnService;
import android.os.Build;
import android.os.Bundle;
import android.preference.PreferenceManager;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;

import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.NotificationManagerCompat;
import androidx.databinding.ObservableArrayList;
import androidx.databinding.ObservableField;
import androidx.databinding.ObservableList;
import androidx.localbroadcastmanager.content.LocalBroadcastManager;

import com.google.android.material.snackbar.Snackbar;

import java.io.FileNotFoundException;
import java.io.IOException;

import de.flyingsnail.ipv6droid.R;
import de.flyingsnail.ipv6droid.android.signinginterface.CSRIntentManager;
import de.flyingsnail.ipv6droid.android.signinginterface.CertPathChangedCallback;
import de.flyingsnail.ipv6droid.android.signinginterface.CertSupplierArrayAdapter;
import de.flyingsnail.ipv6droid.android.statusdetail.StatisticsActivity;
import de.flyingsnail.ipv6droid.android.vpnrun.VpnStatusReport;
import de.flyingsnail.ipv6droid.databinding.ActivityMainBinding;
import de.flyingsnail.ipv6droid.transport.TunnelSpec;

/**
 * Main activity as generated by Android Studio, plus Code to start the service when user clicks.
 */
public class MainActivity extends AppCompatActivity {

    private ActivityMainBinding binding;
    /**
     * The tag to use for logging
     */
    private static final String TAG = MainActivity.class.getName();
    private static final int REQUEST_START_VPN = 1;
    // private static final int REQUEST_SETTINGS = 2;
    private static final int REQUEST_STATISTICS = 3;
    public static final String SHOW_NOTIFICATIONS = "show-notifications";

    /** A TextView that presents in natural language, what is going on */
    private TextView statusText;
    /** A ProgressBar that visualizes the progress of building the tunnel */
    private ProgressBar progress;
    /** An ImageView that visualizes the current status of the tunnel */
    private ImageView status;
    /** An additional start button that is shown if we're just waiting for the user to start */
    private Button redundantStartButton;
    /** The ListView that is going to list all available tunnels */
    private ListView providerListView;
    /** A TextView that presents the reason for the current status, if this represents a fault */
    private TextView causeView;
    /** An observable tunnelspec. This is dealt with by CertPathChangedCallback. */
    private final ObservableField<TunnelSpec> tunnelSpec = new ObservableField<>();
    /** the list of apps (packages) available as suppliers of certification paths. */
    private final ObservableList<String> certPathSuppliers = new ObservableArrayList<>();

    /**
     * The Action name for a vpn stop broadcast intent.
     */
    public static final String BC_STOP = MainActivity.class.getName() + ".STOP";

    /**
     * The Action name for a status update request broadcast.
     */
    public static final String BC_STATUS_UPDATE = MainActivity.class.getName() + ".STATUS_REQUEST";

    /**
     * The receiver for status broadcasts from the IPv6DroidVpnService.
     */
    private StatusReceiver statusReceiver;

    /**
     * An object implementing TunnelPersisting, i.e. a Binder-based DAO to persistent tunnel storage.
     */
    private TunnelPersisting tunnelPersisting;
    private ActivityResultLauncher<String> requestPermissionLauncher;
    private CSRIntentManager csrIntentManager;

    /**
     * Overridden method from activity, initialises the activity and restores any previously saved
     * state information
     * @param savedInstanceState the Bundle to which state was saved previously.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityMainBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        PreferenceManager.setDefaultValues(getApplicationContext(), R.xml.preferences, false);
        SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());

        requestPermissionLauncher = registerForActivityResult(new ActivityResultContracts.RequestPermission(),
                isGranted -> {
                    if (!isGranted) {
                        SharedPreferences.Editor editor = preferences.edit();
                        editor.putBoolean(SHOW_NOTIFICATIONS, false);
                        editor.apply();
                    }
                });


        setSupportActionBar(binding.mainToolbar);
        binding.mainToolbar.setLogo(R.drawable.ic_launcher);

        // init handles to GUI elements
        statusText = binding.statusText;
        progress = binding.progressBar;
        status = binding.statusImage;
        redundantStartButton = binding.redundantStartButton;
        providerListView = binding.providerList;
        causeView = binding.cause;
        ArrayAdapter<String> adapter = new CertSupplierArrayAdapter(MainActivity.this,
                R.layout.providerlist_template, certPathSuppliers);
        // not required, ArrayAdapter is monitoring its list! certPathSuppliers.addOnListChangedCallback(new SupplierChangedCallback(adapter));
        providerListView.setAdapter(adapter);
        providerListView.setOnItemClickListener(this::onSupplierEntryClicked);
        csrIntentManager = new CSRIntentManager(this, certPathSuppliers);

        if (statusReceiver == null)
            statusReceiver = new StatusReceiver();

        // setup the intent filter for status broadcasts
        IntentFilter statusIntentFilter = new IntentFilter(VpnStatusReport.BC_STATUS);

        // Registers the StatusReceiver and its intent filter
        LocalBroadcastManager.getInstance(this).registerReceiver(statusReceiver,
                statusIntentFilter);

        // load tunnels list persisted from last session
        tunnelPersisting = new TunnelPersistingFile(getApplicationContext());
        try {
            Tunnels tunnels = tunnelPersisting.readTunnels();
            TunnelSpec active = tunnels.getActiveTunnel();
            if (active != null) {
                tunnelSpec.set(active);
            }
        } catch (FileNotFoundException e) {
            Log.i(TAG, "Could not load persisted tunnels - probably first invocation", e);
        } catch (IOException e) {
            Log.e(TAG, "Could not load persisted tunnels", e);
        }
        statusReceiver.updateUi();

        try {
            if (isCertificateRequestRequired()) {
                requestCertificate();
            }
        } catch (IOException e) {
            showExceptionAsCause(e);
        }

        requestStatus();
    }

    /**
     * This overridden method is called before the instance gets destroyed.
     */
    @Override
    protected void onDestroy() {
        // switch off ui updates
        LocalBroadcastManager.getInstance(this).unregisterReceiver(statusReceiver);
        statusReceiver = null;
        csrIntentManager.close();
        csrIntentManager = null;
        super.onDestroy();
    }

    /**
     * This overridden method gets called when the menu should be created.
     * @param menu the Menu to inflate to
     * @return a boolean, always true
     */
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.main, menu);
        return true;
    }

    /**
     * Start the system-managed setup of VPN. This is the overloaded method suitable as a
     * declared callback in layout xml definitions.
     * @param clickedView is the View where the click occurred. This parameter is not used.
     */
    public void startVPN(View clickedView) {
        // Start system-managed intent for VPN
        Intent systemVpnIntent = VpnService.prepare(clickedView == null ?
                this : clickedView.getContext());
        if (systemVpnIntent != null) {
            startActivityForResult(systemVpnIntent, REQUEST_START_VPN);
        } else {
            onActivityResult (REQUEST_START_VPN, RESULT_OK, null);
        }
    }

    /**
     * This overridden method restores its state from a Bundle.
     * @param savedInstanceState the Bundle containing the saved state.
     */
    @Override
    protected void onRestoreInstanceState(Bundle savedInstanceState) {
        super.onRestoreInstanceState(savedInstanceState);
        requestStatus();
    }

    @Override
    protected void onPause() {
        super.onPause();
        TunnelSpec currentSpec = tunnelSpec.get();
        if (currentSpec != null && statusReceiver.isTunnelProven()) {
            Log.i (TAG, "We have an updated tunnel list and will write it back to cache");
            final Tunnels tunnels = convertToTunnels(currentSpec);
            try {
                tunnelPersisting.writeTunnels(tunnels);
            } catch (Exception e) {
                Log.e(TAG, "Could not write tunnel information to private file", e);
            }
        }
    }

    /**
     * Callback to inform that user clicked onto one of the suppliers in the list.
     * @param adapterView the View of the list itself
     * @param view the View of the item in the list, that was clicked
     * @param position an int giving the position in the list
     * @param id a long giving the ID of the row clicked
     */
    public void onSupplierEntryClicked(AdapterView<?> adapterView, View view, int position, long id) {
        final String clickedSupplier = certPathSuppliers.get(position);
        if (isCertificateRequestRequired()) {
            try {
                requestCertificate(clickedSupplier);
            } catch (IOException e) {
                showExceptionAsCause(e);
            }
        } else {
            Snackbar.make(view, getString(R.string.confirmRequestNewCertificate), Snackbar.LENGTH_LONG)
                    .setAnchorView(view)
                    .setAction(R.string.request, (v) -> {
                        try {
                            requestCertificate(clickedSupplier);
                        } catch (IOException e) {
                            showExceptionAsCause(e);
                        }
                    })
                    .show();
        }
    }

    /**
     * Displays exception information in the "cause" text field.
     * @param cause the Throwable giving the reason (hopefully)
     */
    private void showExceptionAsCause(final Throwable cause) {
        final String message = cause.getLocalizedMessage();
        final Throwable cause2 = cause.getCause();
        final String rootCause = cause2 == null ? null : cause2.getLocalizedMessage();
        causeView.setText(
                String.format("%s (%s) [%s (%s)]",
                        message == null ? "--" : message,
                        cause.getClass().getSimpleName(),
                        rootCause == null ? "--" : rootCause,
                        cause2 == null ? "--" : cause2.getClass().getSimpleName())
        );
        causeView.setVisibility(VISIBLE);
    }

    private static Tunnels convertToTunnels(TunnelSpec currentSpec) {
        Tunnels tunnels = new Tunnels();
        if (currentSpec != null) {
            tunnels.add(currentSpec);
        }
        tunnels.setActiveTunnel(currentSpec);
        return tunnels;
    }

    @Override
    protected void onResume() {
        super.onResume();

        // update status
        requestStatus();
    }

    public boolean isCertificateRequestRequired() {
        TunnelSpec currentSpec = tunnelSpec.get();
        return (currentSpec == null || !currentSpec.isEnabled());
    }

    /**
     * Start the settings setup activity via Intent.
     */
    private void openSettings () {
        Intent settingsIntent = new Intent(this, SettingsActivity.class);
        settingsIntent.setPackage(getApplicationContext().getPackageName());
        startActivity(settingsIntent);
    }

    /**
     * Try to request a certificate with the current configuration.
     * Might result in the user being flagged to make a selection.
     * @throws IOException in case the CSR could not be sent to a supplier app.
     */
    private void requestCertificate() throws IOException {
        // do we have exactly one supplier? Then, let's use that one without further ado!
        if (certPathSuppliers.size() == 1) {
            requestCertificate(certPathSuppliers.get(0));
            providerListView.setSelection(0);
        } else {
            // is a supplier selected in the list view?
            Object selectedThing = providerListView.getSelectedItem();
            if (selectedThing instanceof String) {
                requestCertificate((String) selectedThing);
            } else {
                providerListView.setElevation(0.5f);
                Toast.makeText(this, R.string.provider_required , Toast.LENGTH_SHORT)
                        .show();
            }
        }
    }

    /**
     * Request certificate from the given service provider (determining the app).
     * @param supplier a String giving the package name of the provider to ask.
     */
    private void requestCertificate(String supplier) throws IOException {
        assert(certPathSuppliers.contains(supplier));
        CertPathChangedCallback callback = new CertPathChangedCallback(tunnelSpec,
                csrIntentManager.getCertHelper(), this);
        ObservableList<String> certPath = new ObservableArrayList<>();
        certPath.addOnListChangedCallback(callback);
        if (!certPathSuppliers.isEmpty()) {
            csrIntentManager.requestCertificate(certPathSuppliers.get(0), certPath);
        }
    }


    /**
     * Start the detached statistics view
     */
    public void openStatistics () {
        // Start system-managed intent for VPN
        Intent settingsIntent = new Intent(this, StatisticsActivity.class);
        settingsIntent.setPackage(getApplicationContext().getPackageName());
        startActivityForResult(settingsIntent, REQUEST_STATISTICS);
    }

    /**
     * Stop the VPN service/thread.
     */
    public void stopVPN () {
        onPause(); // functionally equivalent to a pause of our activity.
        Intent statusBroadcast = new Intent(BC_STOP);
        // Broadcast locally
        LocalBroadcastManager.getInstance(this).sendBroadcast(statusBroadcast);
    }

    /**
     * Broadcast a status update request. If there's a IPv6DroidVpnService out there, it will respond
     * with a standard status message.
     */
    private void requestStatus () {
        Intent statusBroadcast = new Intent(BC_STATUS_UPDATE);
        // Broadcast locally
        LocalBroadcastManager.getInstance(this).sendBroadcast(statusBroadcast);
    }

    /**
     * This is a callback that is going to be called by Android if the user agreed to starting
     * a VPN by this app.
     *
     * @param requestCode an int that should be the magic number REQUEST_START_VPN
     * @param resultCode an int that should be the magic number RESULT_OK
     * @param data an Intent
     */
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == REQUEST_START_VPN && resultCode == RESULT_OK) {
            // request permission to show notification if not granted, but continue anyway
            checkAndRequestNotificationPermission();

            Intent intent = new Intent(this, IPv6DroidVpnService.class).setAction("android.net.VpnService");
            Tunnels tunnels = convertToTunnels(tunnelSpec.get());
            if (tunnels.isTunnelActive()) {
                // Android's Parcel system doesn't handle subclasses well, so...
                intent.putExtra(IPv6DroidVpnService.EXTRA_CACHED_TUNNELS, tunnels.getAndroidSerializable());
            }
            if (Build.VERSION.SDK_INT >= 26) {
                startForegroundService(intent);
            } else {
                startService(intent);
            }
        }
    }

    private void checkAndRequestNotificationPermission() {
        SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
        if (preferences.getBoolean(SHOW_NOTIFICATIONS, true) &&
                !NotificationManagerCompat.from(this).areNotificationsEnabled()) {
            requestPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS);
        }
    }


    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == R.id.action_connect) {
                startVPN(item.getActionView());
                return true;
        }
        if (item.getItemId() == R.id.action_disconnect) {
            stopVPN();
            return true;
        }

        if (item.getItemId() == R.id.action_settings) {
            openSettings();
            return true;
        }

        if (item.getItemId() == R.id.action_help) {
            openHelp();
            return true;
        }

        if (item.getItemId() == R.id.action_subscribe) {
            try {
                requestCertificate();
            } catch (IOException e) {
                showExceptionAsCause(e);
            }
            return true;
        }

        if (item.getItemId() == R.id.action_show_statistics) {
            openStatistics();
            return true;
        }

        return false;
    }

    private void openHelp() {
        Intent helpIntent = new Intent(Intent.ACTION_VIEW);
        helpIntent.setDataAndType(Uri.parse("https://github.com/pelzvieh/IPv6Droid/wiki"), "text/html");
        helpIntent.addCategory(Intent.CATEGORY_BROWSABLE);
        startActivity(helpIntent);
    }

    /** Inner class to handle status updates */
    private class StatusReceiver extends BroadcastReceiver {
        /** The last received status report - including a updatedTunnelList if that was read for that update */
        private VpnStatusReport statusReport = new VpnStatusReport(null);

        public boolean isTunnelProven() {
            return statusReport.isTunnelProvedWorking();
        }

        private void updateUi () {
            int imageRes = R.drawable.off;
            VpnStatusReport.Status status = statusReport.getStatus();
            Log.i(TAG, "received status update: " + statusReport);

            switch (status) {
                case Connected:
                    imageRes = R.drawable.transmitting;
                    break;
                case Idle:
                    imageRes = R.drawable.off;
                    break;
                case Connecting:
                    imageRes = R.drawable.pending;
                    break;
                case Disturbed:
                    imageRes = R.drawable.disturbed;
                    break;
            }
            MainActivity.this.status.setImageResource(imageRes);
            if (statusReport.getProgressPerCent() > 0) {
                MainActivity.this.progress.setIndeterminate(false);
                MainActivity.this.progress.setProgress(statusReport.getProgressPerCent());
            } else
                MainActivity.this.progress.setIndeterminate(true);

            if (status == VpnStatusReport.Status.Idle) {
                redundantStartButton.setVisibility(VISIBLE);
                MainActivity.this.progress.setVisibility(View.INVISIBLE);
                MainActivity.this.statusText.setVisibility(View.INVISIBLE);
            } else {
                redundantStartButton.setVisibility(View.INVISIBLE);
                MainActivity.this.progress.setVisibility(VISIBLE);
                MainActivity.this.statusText.setVisibility(VISIBLE);
            }
            providerListView.setEnabled(status == VpnStatusReport.Status.Idle);

            // show activity text
            if (statusReport.getActivity() != 0)
                MainActivity.this.statusText.setText(getResources().getString(statusReport.getActivity()));

            // show tunnel information
            TunnelSpec currentSpec = tunnelSpec.get();
            if (currentSpec != null) {
                Log.d(TAG, "Tunnel is set");
                binding.tunnelTitle.setText(currentSpec.getTunnelName());
                binding.tunnelDetail.setText(
                        String.format("%s ➡️ %s\n🗓️ %tF",
                                currentSpec.getIpv6Endpoint().getHostAddress(),
                                currentSpec.getIPv4Pop().getHostName(),
                                currentSpec.getExpiryDate())
                        );
            } else {
                Log.d(TAG, "No tunnels are set");
                binding.tunnelTitle.setText("--");
                binding.tunnelDetail.setText("-/-");
            }
            Throwable cause = statusReport.getCause();
            if (cause != null) {
                showExceptionAsCause(cause);
            } else
                causeView.setVisibility(View.INVISIBLE);
        }

        @Override
        public void onReceive(Context context, Intent intent) {
            statusReport = (VpnStatusReport)intent.getSerializableExtra(VpnStatusReport.EDATA_STATUS_REPORT);
            updateUi();
        }
    }
}
