/*
 *
 *  * Copyright (c) 2025 Dr. Andreas Feldner.
 *  *
 *  *     This program is free software; you can redistribute it and/or modify
 *  *     it under the terms of the GNU General Public License as published by
 *  *     the Free Software Foundation; either version 2 of the License, or
 *  *     (at your option) any later version.
 *  *
 *  *     This program is distributed in the hope that it will be useful,
 *  *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  *     GNU General Public License for more details.
 *  *
 *  *     You should have received a copy of the GNU General Public License along
 *  *     with this program; if not, write to the Free Software Foundation, Inc.,
 *  *     51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *  *
 *  * Contact information and current version at http://www.flying-snail.de/IPv6Droid
 *
 *
 */

buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath libs.gradle
    }
}
apply plugin: 'com.android.application'

repositories {
    mavenLocal()
    mavenCentral()
    google()
}

// Create a variable called keystorePropertiesFile, and initialize it to your
// keystore.properties file, in the rootProject folder.
def keystorePropertiesFile = rootProject.file("keystore.local.properties")

// Initialize a new Properties() object called keystoreProperties.
def keystoreProperties = new Properties()

// Load your keystore.properties file into the keystoreProperties object.
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    if (keystoreProperties.containsKey("keyAlias")) {
        signingConfigs {
            release {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
            }
        }
    }

    compileSdk 35

    defaultConfig {
        versionCode 85
        versionName "2.99f"
        minSdkVersion 23
        targetSdkVersion 35
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
    }
    packagingOptions {
        resources {
            pickFirsts += ['META-INF/ASL2.0', 'META-INF/LICENSE', 'META-INF/README', 'META-INF/INDEX.LIST', 'META-INF/DEPENDENCIES']
        }
    }


    buildTypes {
        release {
            defaultConfig
        }
        if (keystoreProperties.containsKey("keyAlias")) {
            signed {
                signingConfig signingConfigs.release
            }
        }

        debug {
            matchingFallbacks = []
        }
    }

    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }


    buildFeatures {
        buildConfig = true
        dataBinding = true
        viewBinding = true
    }

    lint {
        abortOnError false
        checkReleaseBuilds true
    }
    namespace 'de.flyingsnail.ipv6droid'
}

dependencies {
    implementation libs.androidx.annotation
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.core
    implementation libs.androidx.localbroadcastmanager
    implementation libs.bctls.jdk15to18
    implementation libs.bcpkix.jdk15to18
    implementation libs.androidx.preference
    implementation libs.androidx.databinding.common
    implementation libs.androidx.databinding.runtime
    implementation libs.material
    implementation libs.rxjava
    testImplementation libs.junit
    testImplementation libs.mockito.core
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.rules
    // Optional -- UI testing with Espresso
    // androidTestImplementation "androidx.test.espresso:espresso-core:$espressoVersion"
    // Optional -- UI testing with UI Automator
    // androidTestImplementation "androidx.test.uiautomator:uiautomator:$uiAutomatorVersion"
    // Optional -- UI testing with Compose
    // androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
}
